version: 1.0.{build}
environment:
  matrix:
  - MSYSTEM: MINGW64
    BASH: C:\msys64\usr\bin\bash
    CC: x86_64-w64-mingw32-gcc
    MSYS_PACKAGES: mingw-w64-x86_64-ruby mingw-w64-x86_64-gtk3 mingw-w64-x86_64-libiconv
    PATH: c:\msys64\mingw64\usr\bin;c:\msys64\mingw64\bin;%PATH%
install:
- cmd: >-
    if defined MSYSTEM (%BASH% -lc "pacman -Suuy --noconfirm ${MSYS_PACKAGES}")

    if defined MSYSTEM (%BASH% -lc "pacman -Suuy --noconfirm ${MSYS_PACKAGES} && pacman -Sc --noconfirm")
build_script:
- cmd: if defined BASH (%BASH% -lc "cd $(cygpath ${APPVEYOR_BUILD_FOLDER}) && ./build.sh")
test_script:
- cmd: if defined BASH (%BASH% -lc "cd $(cygpath ${APPVEYOR_BUILD_FOLDER}) && ./build.sh test")
